# Generated by Django 6.0.4 on 2026-04-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('Id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100, unique=True)),
                ('Precio', models.IntegerField()),
                ('Despcrion', models.TextField()),
                ('imagen', models.ImageField(upload_to='react/src/assets/')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100, unique=True)),
                ('Password', models.CharField(max_length=200, verbose_name='constraseña')),
            ],
        ),
    ]
