# Generated by Django 6.0.4 on 2026-04-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Despcrion',
            new_name='Descripcion',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AddField(
            model_name='categoria',
            name='Id_categoria',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='Id_usuario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
